### VADER

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
columns = ['id','text_final', 'polarity', 'VADER_score']

df_vader_train = pd.read_csv('VADER_train.csv',
                     header = 0, 
                     usecols = [1,2,3], 
                     names=columns,
                     encoding ='ISO-8859-1')

In [3]:
df_vader_train.head()

text_final  polarity  VADER_score
0  @USER @URL - aw  , that ' s a bummer . you sho...         0      -0.3818
1  is upset that he can not update his facebook b...         0      -0.7500
2  @USER i dived many times for the ball . manage...         0       0.4939
3     my whole body feels itchy and like its on fire         0      -0.2500
4  @USER no , it ' s not behaving at all . i am m...         0      -0.6597

### Create column VADER_binary: 0 if lower or equal to 0, 1 otherwise

In [5]:
df_vader_train['VADER_binary'] = (df_vader_train['VADER_score'] > 0).astype(int)

In [8]:
df_vader_train.head()

text_final  polarity  VADER_score  \
0  @USER @URL - aw  , that ' s a bummer . you sho...         0      -0.3818   
1  is upset that he can not update his facebook b...         0      -0.7500   
2  @USER i dived many times for the ball . manage...         0       0.4939   
3     my whole body feels itchy and like its on fire         0      -0.2500   
4  @USER no , it ' s not behaving at all . i am m...         0      -0.6597   

   VADER_binary  
0             0  
1             0  
2             1  
3             0  
4             0

## 1st threshold 0

In [9]:
vader_0 = df_vader_train.drop(df_vader_train[(df_vader_train.VADER_score == 0)].index)

### Polarity 0

In [24]:
type(vader_0['polarity'])

pandas.core.series.Series

In [26]:
y_true0 = vader_0['polarity']

In [27]:
y_true0.tolist()

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [28]:
pd.Series(y_true0).values

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

### VADER predictions 0

In [29]:
type(vader_0['VADER_binary'])


pandas.core.series.Series

In [30]:
y_pred0 = vader_0['VADER_binary']


In [31]:
y_pred0.tolist()

[0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,


In [32]:
pd.Series(y_pred0).values

array([0, 0, 1, ..., 1, 1, 1])

### confusion matrix 0

In [16]:
from sklearn.metrics import confusion_matrix

In [33]:
confusion_matrix(y_true0, y_pred0)

array([[352567, 259535],
       [ 83824, 509193]], dtype=int64)

In [34]:
from pandas_ml import ConfusionMatrix

In [35]:
binary_confusion_matrix = ConfusionMatrix(y_true0, y_pred0)

In [36]:
print("Binary confusion matrix:\n%s" % binary_confusion_matrix)

Binary confusion matrix:
Predicted       0       1  __all__
Actual                            
0          352567  259535   612102
1           83824  509193   593017
__all__    436391  768728  1205119


### Accuracy 0

In [37]:
from sklearn.metrics import accuracy_score

In [39]:
accuracy_score(y_true0, y_pred0)

0.7150829088247717

In [40]:
accuracy = 0
for prediction,correct in zip(y_pred0, y_true0):
    if prediction>0 and correct==1 or prediction<=0 and correct==0:
        accuracy += 1
print(accuracy/len(y_pred0))

0.7150829088247717


### Threshold 025

In [41]:
vader_025 = df_vader_train.drop(df_vader_train[(df_vader_train.VADER_score > -0.25) & (df_vader_train.VADER_score < 0.25)].index)

In [42]:
vader_025.head()

text_final  polarity  VADER_score  \
0  @USER @URL - aw  , that ' s a bummer . you sho...         0      -0.3818   
1  is upset that he can not update his facebook b...         0      -0.7500   
2  @USER i dived many times for the ball . manage...         0       0.4939   
3     my whole body feels itchy and like its on fire         0      -0.2500   
4  @USER no , it ' s not behaving at all . i am m...         0      -0.6597   

   VADER_binary  
0             0  
1             0  
2             1  
3             0  
4             0

### Polarity 025


In [43]:
type(vader_025['polarity'])


pandas.core.series.Series

In [44]:
y_true025 = vader_025['polarity']


In [45]:
y_true025.tolist()


[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [46]:
pd.Series(y_true025).values

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [47]:
### VADER predictions 025

type(vader_025['VADER_binary'])
y_pred025 = vader_025['VADER_binary']
y_pred025.tolist()
pd.Series(y_pred025).values

array([0, 0, 1, ..., 1, 1, 1])

### accuracy 025

In [48]:
accuracy_score(y_true025, y_pred025)

0.7413869116404634

In [49]:
accuracy = 0
for prediction,correct in zip(y_pred025, y_true025):
    if prediction>0 and correct==1 or prediction<=0 and correct==0:
        accuracy += 1
print(accuracy/len(y_pred025))

0.7413869116404634


### confusion matrix 025

In [50]:
confusion_matrix(y_true025, y_pred025)

array([[285724, 205566],
       [ 60746, 477734]], dtype=int64)

In [52]:
binary_confusion_matrix025 = ConfusionMatrix(y_true025, y_pred025)
print("Binary confusion matrix:\n%s" % binary_confusion_matrix025)

Binary confusion matrix:
Predicted       0       1  __all__
Actual                            
0          285724  205566   491290
1           60746  477734   538480
__all__    346470  683300  1029770


### Threshold 035


In [53]:
vader_035 = df_vader_train.drop(df_vader_train[(df_vader_train.VADER_score > -0.35) & (df_vader_train.VADER_score < 0.35)].index)

In [54]:
vader_035.head()

text_final  polarity  VADER_score  \
0  @USER @URL - aw  , that ' s a bummer . you sho...         0      -0.3818   
1  is upset that he can not update his facebook b...         0      -0.7500   
2  @USER i dived many times for the ball . manage...         0       0.4939   
4  @USER no , it ' s not behaving at all . i am m...         0      -0.6597   
6                                         need a hug         0       0.4767   

   VADER_binary  
0             0  
1             0  
2             1  
4             0  
6             1

In [55]:
### Polarity 035
type(vader_035['polarity'])
y_true035 = vader_035['polarity']
y_true035.tolist()
pd.Series(y_true035).values

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [56]:
### VADER predictions 035

type(vader_035['VADER_binary'])
y_pred035 = vader_035['VADER_binary']
y_pred035.tolist()
pd.Series(y_pred035).values

array([0, 0, 1, ..., 1, 1, 1])

In [59]:
### accuracy 035

In [57]:
accuracy_score(y_true035, y_pred035)

0.7549302243656203

In [58]:
accuracy = 0
for prediction,correct in zip(y_pred035, y_true035):
    if prediction>0 and correct==1 or prediction<=0 and correct==0:
        accuracy += 1
print(accuracy/len(y_pred035))

0.7549302243656203


In [60]:
### confusion matrix 035

In [61]:
confusion_matrix(y_true035, y_pred035)

array([[231546, 175249],
       [ 44583, 445640]], dtype=int64)

In [62]:
binary_confusion_matrix035 = ConfusionMatrix(y_true035, y_pred035)
print("Binary confusion matrix:\n%s" % binary_confusion_matrix035)

Binary confusion matrix:
Predicted       0       1  __all__
Actual                            
0          231546  175249   406795
1           44583  445640   490223
__all__    276129  620889   897018


### Threshold 0.5

In [63]:
vader_05 = df_vader_train.drop(df_vader_train[(df_vader_train.VADER_score > -0.50) & (df_vader_train.VADER_score < 0.50)].index)

In [64]:
vader_05.head()

text_final  polarity  VADER_score  \
1   is upset that he can not update his facebook b...         0      -0.7500   
4   @USER no , it ' s not behaving at all . i am m...         0      -0.6597   
7   @USER hey long time no see ! yes .  rains a bi...         0       0.8070   
12  @USER i could not bear to watch it . and i tho...         0      -0.5994   
16  hollis ' death scene will hurt me severely to ...         0      -0.9081   

    VADER_binary  
1              0  
4              0  
7              1  
12             0  
16             0

In [65]:
### Polarity 05
type(vader_05['polarity'])
y_true05 = vader_05['polarity']
y_true05.tolist()
pd.Series(y_true05).values

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [66]:
### VADER predictions 05

type(vader_05['VADER_binary'])
y_pred05 = vader_05['VADER_binary']
y_pred05.tolist()
pd.Series(y_pred05).values

array([0, 0, 1, ..., 1, 1, 1])

In [67]:
accuracy_score(y_true05, y_pred05)

0.7805732241035493

In [68]:
accuracy = 0
for prediction,correct in zip(y_pred05, y_true05):
    if prediction>0 and correct==1 or prediction<=0 and correct==0:
        accuracy += 1
print(accuracy/len(y_pred05))

0.7805732241035493


In [69]:
confusion_matrix(y_true05, y_pred05)

array([[146292, 107386],
       [ 24877, 324211]], dtype=int64)

In [70]:
binary_confusion_matrix05 = ConfusionMatrix(y_true05, y_pred05)
print("Binary confusion matrix:\n%s" % binary_confusion_matrix05)

Binary confusion matrix:
Predicted       0       1  __all__
Actual                            
0          146292  107386   253678
1           24877  324211   349088
__all__    171169  431597   602766
